[package]
name = "zed-mcp-server-repomix"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
path = "src/mcp_server_repomix.rs"
crate-type = ["cdylib"]

[dependencies]
schemars = "0.8"
serde = "1.0"
zed_extension_api = "0.7.0"
