id = "mcp-server-repomix"
name = "Repomix MCP Server"
description = "Model Context Protocol Server for Repomix"
version = "0.1.0"
schema_version = 1
authors = ["Matías López <34432076+mlopezgez@users.noreply.github.com>"]
repository = "https://github.com/akbxr/zed-mcp-server-context7"

[context_servers.mcp-server-repomix]
name = "Repomix MCP Server"
